spring:
  datasource:
    username: ivan
    password: rootroot
    url: jdbc:postgresql://localhost:5432/searchengine_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false