server:
  port: 8080

spring:
  application:
    name: search-engine
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    clear-checksums: false
  profiles:
    active: dev

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Lenta
    - url: https://beltexoptic.by
      name: Белтекс Оптик
    - url: https://www.onliner.by/
      name: Onliner
    - url: https://atlant.by/
      name: Atlant